# Generated by Django 5.2.7 on 2025-10-15 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserHealthMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wakeup_datetime", models.DateTimeField()),
                ("sleeping_datetime", models.DateTimeField()),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight in kg", max_digits=5
                    ),
                ),
                (
                    "thigh_length",
                    models.DecimalField(
                        decimal_places=2, help_text="Thigh length in cm", max_digits=5
                    ),
                ),
                (
                    "hip_length",
                    models.DecimalField(
                        decimal_places=2, help_text="Hip length in cm", max_digits=5
                    ),
                ),
                ("recorded_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_date"],
                "unique_together": {("user", "recorded_date")},
            },
        ),
    ]
