# Generated by Django 5.2.7 on 2025-10-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0003_auto_20251015_1421"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhealthmetrics",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Progress photo",
                null=True,
                upload_to="health_metrics/",
            ),
        ),
    ]
