# Generated by Django 5.2.7 on 2025-10-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0004_userhealthmetrics_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TrainingSession",
        ),
    ]
