# Generated by Django 5.2.7 on 2025-10-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0005_delete_trainingsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userhealthmetrics",
            name="recorded_date",
            field=models.DateField(),
        ),
    ]
